version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # Uncomment and set these in your .env file as needed
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - WANDB_API_KEY=${WANDB_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: python3

  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=hackathon
      - POSTGRES_PASSWORD=hackathon
      - POSTGRES_DB=hackathon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Uncomment if you need vector database
  # chroma:
  #   image: chromadb/chroma
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - chroma_data:/chroma/chroma

volumes:
  postgres_data:
  chroma_data: